// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtyVQs_fVmm1qDpi1vP75pE5OZNis75So',
    appId: '1:849631668806:web:64bef7494336c3fa743847',
    messagingSenderId: '849631668806',
    projectId: 'to-do-app-647f8',
    authDomain: 'to-do-app-647f8.firebaseapp.com',
    storageBucket: 'to-do-app-647f8.appspot.com',
    measurementId: 'G-BYFP9P9DC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6FGoj6e5m2A2WWTm3o7jaPFSga9hGNp8',
    appId: '1:849631668806:android:e26f9815138eb880743847',
    messagingSenderId: '849631668806',
    projectId: 'to-do-app-647f8',
    storageBucket: 'to-do-app-647f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJVkLKEeu4ncgj3uhlmwwHXKTm6sRJ5KY',
    appId: '1:849631668806:ios:c7089b895706c7e3743847',
    messagingSenderId: '849631668806',
    projectId: 'to-do-app-647f8',
    storageBucket: 'to-do-app-647f8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJVkLKEeu4ncgj3uhlmwwHXKTm6sRJ5KY',
    appId: '1:849631668806:ios:b9ea184fddc7503f743847',
    messagingSenderId: '849631668806',
    projectId: 'to-do-app-647f8',
    storageBucket: 'to-do-app-647f8.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
